"""Gmail delivery via the Gmail MCP server (HTTP transport)."""
import json
import urllib.request
import urllib.error
from datetime import datetime
from zoneinfo import ZoneInfo

from config import GMAIL_MCP_URL, ALERT_EMAIL_TO, DRY_RUN

ET = ZoneInfo("America/New_York")


def _now_et_str() -> str:
    return datetime.now(ET).strftime("%H:%M ET")


def _mcp_call(method: str, params: dict) -> dict:
    """
    Send a JSON-RPC 2.0 call to the Gmail MCP HTTP server.
    Returns the parsed JSON response or raises on error.
    """
    payload = json.dumps({
        "jsonrpc": "2.0",
        "id": 1,
        "method": method,
        "params": params,
    }).encode()

    req = urllib.request.Request(
        GMAIL_MCP_URL,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        raise RuntimeError(f"Gmail MCP HTTP {e.code}: {body}") from e


def _build_digest_body(alerts_by_type: dict[str, list[str]]) -> str:
    """Format alerts into a clean digest email body."""
    section_headers = {
        "UNUSUAL_VOL": "── UNUSUAL VOL ──────────────────",
        "GEX": "── GEX EXTREME ──────────────────",
        "ROLL": "── ROLL OPPORTUNITY ─────────────",
        "EARNINGS": "── EARNINGS VOL ─────────────────",
    }
    lines = [f"Options Alert Digest — {_now_et_str()}", ""]
    for key, header in section_headers.items():
        if key in alerts_by_type and alerts_by_type[key]:
            lines.append(header)
            for txt in alerts_by_type[key]:
                lines.append(f"  {txt}")
            lines.append("")
    lines.append("─" * 40)
    lines.append("Generated by Options Alert System")
    return "\n".join(lines)


def send_digest(alerts_by_type: dict[str, list[str]], is_eod: bool = False) -> bool:
    """
    Send a batch digest email.
    alerts_by_type: {"UNUSUAL_VOL": [...], "GEX": [...], ...}
    Returns True on success.
    """
    total = sum(len(v) for v in alerts_by_type.values())
    if total == 0:
        return False

    time_str = _now_et_str()
    if is_eod:
        subject = f"EOD Options Summary — {total} signals — {time_str}"
    else:
        subject = f"Options Alert Digest — {total} signal{'s' if total != 1 else ''} — {time_str}"

    body = _build_digest_body(alerts_by_type)

    if DRY_RUN:
        print("\n" + "=" * 60)
        print("DRY RUN — Email not sent")
        print(f"TO:      {ALERT_EMAIL_TO}")
        print(f"SUBJECT: {subject}")
        print("-" * 60)
        print(body)
        print("=" * 60 + "\n")
        return True

    try:
        result = _mcp_call("tools/call", {
            "name": "send_email",
            "arguments": {
                "to": ALERT_EMAIL_TO,
                "subject": subject,
                "body": body,
            },
        })
        if "error" in result:
            print(f"[gmail] MCP error: {result['error']}")
            return False
        print(f"[gmail] Sent digest: {subject}")
        return True
    except Exception as e:
        print(f"[gmail] Failed to send email: {e}")
        return False


def send_market_open_digest(alerts_by_type: dict[str, list[str]]) -> bool:
    total = sum(len(v) for v in alerts_by_type.values())
    subject = f"Market Open — Options Briefing — {total} signal{'s' if total != 1 else ''} — {_now_et_str()}"
    body = "MARKET OPEN BRIEFING\n\n" + _build_digest_body(alerts_by_type)

    if DRY_RUN:
        print("\n" + "=" * 60)
        print("DRY RUN — Market Open Email not sent")
        print(f"SUBJECT: {subject}")
        print("-" * 60)
        print(body)
        print("=" * 60 + "\n")
        return True

    try:
        result = _mcp_call("tools/call", {
            "name": "send_email",
            "arguments": {
                "to": ALERT_EMAIL_TO,
                "subject": subject,
                "body": body,
            },
        })
        return "error" not in result
    except Exception as e:
        print(f"[gmail] Failed to send market open email: {e}")
        return False


def send_eod_summary(top_signals: list[str]) -> bool:
    time_str = _now_et_str()
    subject = f"EOD Options Summary — {len(top_signals)} top signals — {time_str}"
    body = f"END OF DAY SUMMARY — {time_str}\n\n"
    body += "Top signals ranked by strength:\n"
    for i, sig in enumerate(top_signals, 1):
        body += f"  {i}. {sig}\n"
    body += "\n" + "─" * 40 + "\nGenerated by Options Alert System"

    if DRY_RUN:
        print("\n" + "=" * 60)
        print("DRY RUN — EOD Summary not sent")
        print(f"SUBJECT: {subject}")
        print("-" * 60)
        print(body)
        print("=" * 60 + "\n")
        return True

    try:
        result = _mcp_call("tools/call", {
            "name": "send_email",
            "arguments": {
                "to": ALERT_EMAIL_TO,
                "subject": subject,
                "body": body,
            },
        })
        return "error" not in result
    except Exception as e:
        print(f"[gmail] Failed to send EOD summary: {e}")
        return False
